# Generated by Django 5.2 on 2026-05-08 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Prix du produit au moment de la négociation', max_digits=10)),
                ('buyer_price', models.DecimalField(decimal_places=2, help_text="Prix proposé par l'acheteur", max_digits=10)),
                ('counter_price', models.DecimalField(blank=True, decimal_places=2, help_text='Contre-offre du vendeur (si applicable)', max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix finalement accepté', max_digits=10, null=True)),
                ('buyer_message', models.TextField(blank=True, help_text="Message optionnel de l'acheteur")),
                ('vendor_message', models.TextField(blank=True, help_text='Réponse optionnelle du vendeur')),
                ('counter_message', models.TextField(blank=True, help_text='Message avec la contre-offre')),
                ('buyer_counter_message', models.TextField(blank=True, help_text="Réponse de l'acheteur à la contre-offre")),
                ('status', models.CharField(choices=[('pending', 'En attente vendeur'), ('counter', 'Contre-offre en cours'), ('accepted', 'Acceptée ✅'), ('rejected', 'Refusée ❌'), ('ordered', 'Commandée 🛒'), ('expired', 'Expirée ⏰'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiation', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations_as_vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Négociation',
                'verbose_name_plural': 'Négociations',
                'ordering': ['-created_at'],
            },
        ),
    ]
