# Generated by Django 5.2 on 2026-05-08 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('order_placed', 'Nouvelle commande'), ('order_confirmed', 'Commande confirmée'), ('order_cancelled', 'Commande annulée'), ('order_shipped', 'Commande expédiée'), ('order_delivered', 'Commande livrée'), ('expiry_alert', 'Alerte péremption'), ('negotiation_offer', 'Nouvelle offre'), ('negotiation_accepted', 'Offre acceptée'), ('negotiation_rejected', 'Offre refusée'), ('negotiation_counter', 'Contre-offre'), ('system', 'Système')], default='system', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
