# Generated by Django 5.2 on 2026-05-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('order_placed', 'Nouvelle commande'), ('order_confirmed', 'Commande confirmée'), ('order_cancelled', 'Commande annulée'), ('order_shipped', 'Commande expédiée'), ('order_delivered', 'Commande livrée'), ('expiry_alert', 'Alerte péremption'), ('stock_warning', 'Stock faible'), ('negotiation_offer', 'Nouvelle offre'), ('negotiation_accepted', 'Offre acceptée'), ('negotiation_rejected', 'Offre refusée'), ('negotiation_counter', 'Contre-offre'), ('new_registration', 'Nouvelle inscription'), ('new_offer', 'Nouvelle offre disponible'), ('system', 'Système')], default='system', max_length=30),
        ),
    ]
